BASE_TREE=http://code.qt.io/yocto/meta-qt6.git
BASE_BRANCH=dev
TO_TREE=git@github.com:MontaVista-OpenSourceTechnology/meta-qt6
TO_REMOTE=github
AUTO_PUSH_MASTER="0"
MANUAL_MERGE_BRANCHES="rocko thud dunfell"
FORCE_IF_FAIL="1"
REMOVE_TREE="1"
